### ISSUE TITLE
Flatpack package is not work

### ISSUE THREAD

**Issue by yhojann-cl** [flathub/com.github.suzie97.communique#1] opened 2022-01-18 21:44 UTC
When run app from flathub show a loader and text "OFFLINE" but the button for add feed is disabled, can not add new urls.

https://i.ibb.co/Fn53Tw4/Captura-de-pantalla-de-2022-01-18-18-42-38.png

**Comment by Suzie97** [comment] 2022-05-29 09:51
Thank you for your issue report.

I'm closing this as a duplicate of this issue: https://github.com/Suzie97/Communique/issues/9

**Closed as completed by Suzie97** 2022-05-29 09:51 UTC
